<template>
  <footer class="bg-gray-900 text-white pt-12 pb-8 px-4 section-footer">
    <div
      class="
        mx-auto
        px-4
        container
        overflow-hidden
        flex flex-col
        lg:flex-row
        justify-between
      "
    >
      <a href="/" class="block mr-4 w-1/3">
        <img
          src="/assets/parakeet-logo.png"
          class="w-40 ml-4 lg:ml-0"
          alt="logo"
        />
      </a>
      <div class="w-2/3 block sm:flex text-sm mt-6 lg:mt-0">
        <ul
          class="
            text-gray-700
            list-none
            p-0
            font-thin
            flex flex-col
            text-left
            w-full
          "
        >
          <li
            class="
              inline-block
              py-2
              px-3
              text-white
              uppercase
              font-medium
              tracking-wide
            "
          >
            Products
          </li>
          <li>
            <a
              href="https://getparakeet.dev/why-us"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >Features</a
            >
          </li>
          <li>
            <a
              href="https://docs.getparakeet.dev/dev/integrate"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >Integrations</a
            >
          </li>
          <li>
            <a
              href="https://getparakeet.dev/products"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >Pricing</a
            >
          </li>
          <li>
            <a
              href="/faq"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >FAQ</a
            >
          </li>
        </ul>
        <ul
          class="
            text-gray-700
            list-none
            p-0
            font-thin
            flex flex-col
            text-left
            w-full
          "
        >
          <li
            class="
              inline-block
              py-2
              px-3
              text-white
              uppercase
              font-medium
              tracking-wide
            "
          >
            Company
          </li>
          <li>
            <a
              href="https://policies.getparakeet.dev/Privacy"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >Privacy</a
            >
          </li>
          <li>
            <a
              href="https://policies.getparakeet.dev/ToS"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >Terms of Service</a
            >
          </li>
          <li>
            <a
              href="https://blog.getparakeet.dev/our-commitment"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >Our commitment</a
            >
          </li>
          <li>
            <a
              href="https://getparakeet.dev/abuse"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >Report Abuse</a
            >
          </li>
        </ul>
        <ul
          class="
            text-gray-700
            list-none
            p-0
            font-thin
            flex flex-col
            text-left
            w-full
          "
        >
          <li
            class="
              inline-block
              py-2
              px-3
              text-white
              uppercase
              font-medium
              tracking-wide
            "
          >
            Developers
          </li>
          <li>
            <a
              href="https://docs.getparakeet.dev/dev/api"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >API</a
            >
          </li>
          <li>
            <a
              href="https://docs.getparakeet.dev"
              class="
                inline-block
                py-2
                px-3
                text-gray-500
                hover:text-white
                no-underline
              "
              >Documentation</a
            >
          </li>
        </ul>
        <div class="text-gray-700 flex flex-col w-full">
          <div
            class="
              inline-block
              py-2
              px-3
              text-white
              uppercase
              font-medium
              tracking-wide
            "
          >
            Follow Us
          </div>
          <div class="flex pl-4 justify-start mt-2">
            <a
              class="
                block
                flex
                items-center
                text-gray-300
                hover:text-white
                mr-6
                no-underline
              "
              href="https://twitter/get_parakeet"
            >
              <div v-html="$feathericons['twitter'].toSvg()"></div>
            </a>
            <a
              class="
                block
                flex
                items-center
                text-gray-300
                hover:text-white
                mr-6
                no-underline
              "
              href="https://linkedin.com/in/parakeet-cloud"
            >
              <div v-html="$feathericons['linkedin'].toSvg()"></div>
            </a>
            <a
              class="
                block
                flex
                items-center
                text-gray-300
                hover:text-white
                mr-6
                no-underline
              "
              href="https://github.com/parakeet-cloud"
            >
              <div v-html="$feathericons['github'].toSvg()"></div>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div
      class="pt-4 mt-4 pt-6 text-gray-600 border-t border-gray-800 text-center"
    >
      © 2019 Parakeet Cloud. All rights reserved.
    </div>
  </footer>
</template>

<script>
export default {}
</script>

<style></style>
